table financials
	lineageTag: 0bd644db-b95e-4273-a57e-676850e04fc7

	column Segment
		dataType: string
		lineageTag: cf922890-cb71-4b90-b67c-7b84ecaa2d68
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: eb6e28df-cbcb-45eb-ab73-91bbe3fdb458
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 94b2884b-f42e-4dca-97ff-08cf32bfc1e9
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Discount Band'
		dataType: string
		lineageTag: 6e47aa86-82ce-4f2b-86c8-a5622db210b8
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: double
		lineageTag: f4ea1368-767c-4499-bf41-376e44a24e9c
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Manufacturing Price'
		dataType: int64
		formatString: 0
		lineageTag: 8814f059-14f0-43b8-8dec-a847e9508ce9
		summarizeBy: sum
		sourceColumn: Manufacturing Price

		annotation SummarizationSetBy = Automatic

	column 'Sale Price'
		dataType: int64
		formatString: 0
		lineageTag: fa7aea9b-76af-4d2e-bb35-a715c1d20712
		summarizeBy: sum
		sourceColumn: Sale Price

		annotation SummarizationSetBy = Automatic

	column 'Gross Sales'
		dataType: double
		lineageTag: 22a233dd-dc42-42a8-9f44-f820311ecc33
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discounts
		dataType: double
		lineageTag: 0043020f-02bf-4bcd-b146-3d60c51352b4
		summarizeBy: sum
		sourceColumn: Discounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales
		dataType: double
		lineageTag: 7ecede35-d55b-42b7-b6ac-3a0308d572a4
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COGS
		dataType: double
		lineageTag: 0e3136e5-23c5-4e21-8804-a876592854c8
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 9535518a-09f8-459a-94ff-d74cd60ed9fe
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5f6f1644-aa44-4380-9208-31cd10da564d
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: c98fc715-6a84-4f9c-8e01-ff54d41071dd
			defaultHierarchy: LocalDateTable_e250fbdb-17e8-4011-9d05-2384d3ca982f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 9f8ad611-a7f7-4de5-8640-754810901711
		summarizeBy: sum
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 95362e61-80de-49df-974d-e32962e20823
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 34fbfd55-fa15-472c-b325-ec4a7a6cdbea
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition financials = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(Web.Contents("https://ericsson.sharepoint.com/sites/FAST988/Shared%20Documents/Pipe%20line%20data/Financial%20Sample.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "financials", Kind = "Table"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {"Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}})
				in
				  #"Changed column type"

