table financials
	lineageTag: 2f3b2862-f37f-45c5-aa74-2322aecf314c

	column Segment
		dataType: string
		lineageTag: adff74e7-96b2-43e8-b401-7c04c0e808d9
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 5ca4959c-c92b-4b9a-a5a1-d4585b731089
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: cb8781a4-ead0-4241-8539-c0f708b5b843
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Discount Band'
		dataType: string
		lineageTag: b1eaeedf-9f93-4cec-9c7c-f7dc7099cc85
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: double
		lineageTag: 126b3c0b-7d49-40b8-afb8-f7e439a0da4f
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Manufacturing Price'
		dataType: int64
		formatString: 0
		lineageTag: c548f73e-b797-498d-9887-76411d70d167
		summarizeBy: sum
		sourceColumn: Manufacturing Price

		annotation SummarizationSetBy = Automatic

	column 'Sale Price'
		dataType: int64
		formatString: 0
		lineageTag: 09ad3a1c-6734-4872-920e-3c5ac6b865fa
		summarizeBy: sum
		sourceColumn: Sale Price

		annotation SummarizationSetBy = Automatic

	column 'Gross Sales'
		dataType: double
		lineageTag: 1645ca54-c0c8-4750-b677-46f2a2aae6aa
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discounts
		dataType: double
		lineageTag: 9091b50c-12cd-465e-9555-d47a2710ff9d
		summarizeBy: sum
		sourceColumn: Discounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ' Sales'
		dataType: double
		lineageTag: 44c47323-4ea6-4287-9872-0ba503b5138a
		summarizeBy: sum
		sourceColumn: " Sales"

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COGS
		dataType: double
		lineageTag: 7e8e3824-d5c5-48cf-ac5b-c074da1e51dc
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 4e25ce30-f561-452a-91bb-a16074e1bd37
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b3eb083c-29d5-4822-b998-5084c0cd5d8a
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: fc15987c-d980-4093-a4ec-00fd8b2d1841
			defaultHierarchy: LocalDateTable_ab4db08a-14d5-4ac2-8b38-4e1b78d83b09.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 435ac7e5-8e46-42f4-a838-669b29edd9f5
		summarizeBy: sum
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 712e93cf-8596-4d2c-a66b-36dc416a3de5
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 5e61c4ce-e159-4757-9e03-c977d7cdc1f9
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition financials = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\zsamkuy\OneDrive - Ericsson\Apps\Microsoft Power Query\Uploaded Files\Financial Sample.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "financials", Kind = "Table"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {" Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}})
				in
				  #"Changed column type"

